name = "project-zlpr-website"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "recipe-db"
database_id = "5dc9c411-071e-4313-8858-67051e1f7d37"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "recipe-images"