name = "project-zlpr-website"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "recipe-db"
database_id = "YOUR_DATABASE_ID"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "recipe-images"